const cardsMassive = [
    {
        idItem:    10,
        typeItem:  1,
        fotoUrl:   '/src/img/image 4.png',
        fotoAlt:   't-shirt',
        newItem:   false,
        priceItem: 220,
        titleItem: 'Футболка "Эволюционируй или Эволюционируй или"',
        colors:    [
            { modName: 'blue', txt: 'синий' },
            { modName: 'beige', txt: 'бежевый' },
            { modName: 'grey', txt: 'серый' },
        ],
        sizes:       ['s', 'm', 'l'],
        description: [
            { title: 'Детали:', txt: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%' },
            { title: 'Как выбрать размер:', txt: 'Написать дяде Рику для уточнения.' },
        ],
    },
    {
        idItem:    20,
        typeItem:  1,
        fotoUrl:   '/src/img/image 4.png',
        fotoAlt:   't-shirt',
        newItem:   true,
        priceItem: 1100,
        titleItem: 'Футболка "Эволюционируй или Эволюционируй или"',
        colors:    [
            { modName: 'blue', txt: 'синий' },
            { modName: 'grey', txt: 'серый' },
            { modName: 'beige', txt: 'бежевый' },
            { modName: 'grey', txt: 'серый' },
        ],
        sizes:       ['m', 'l'],
        description: [
            { title: 'Детали:', txt: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%' },
            { title: 'Как выбрать размер:', txt: 'Написать дяде Рику для уточнения.' },
        ],
    },
    {
        idItem:    30,
        typeItem:  2,
        fotoUrl:   '/src/img/image 7.png',
        fotoAlt:   'shirt',
        newItem:   false,
        priceItem: 180,
        titleItem: 'Недохуди "Эволюционируй или Эволюционируй или"',
        colors:    [
            { modName: 'blue', txt: 'синий' },
            { modName: 'beige', txt: 'бежевый' },
            { modName: 'grey', txt: 'серый' },
        ],
        sizes:       ['s', 'm', 'l'],
        description: [
            { title: 'Детали:', txt: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%' },
            { title: 'Как выбрать размер:', txt: 'Написать дяде Рику для уточнения.' },
        ],
    },
    {
        idItem:    40,
        typeItem:  2,
        fotoUrl:   '/src/img/image 7.png',
        fotoAlt:   'shirt',
        newItem:   true,
        priceItem: 1400,
        titleItem: 'Недохуди "С размером 66L Эволюционируй или Эволюционируй или"',
        colors:    [
            { modName: 'blue', txt: 'синий' },
            { modName: 'beige', txt: 'бежевый' },
        ],
        sizes:       ['s', 'm', 'l', 'xxl'],
        description: [
            { title: 'Детали:', txt: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%' },
        ],
    },
    {
        idItem:    50,
        typeItem:  1,
        fotoUrl:   '/src/img/image 4.png',
        fotoAlt:   't-shirt',
        newItem:   true,
        priceItem: 2200,
        titleItem: 'Футболка "У которой нет размеров, но зато есть цвета"',
        colors:    [
            { modName: 'blue', txt: 'синий' },
            { modName: 'beige', txt: 'бежевый' },
            { modName: 'grey', txt: 'серый' },
            { modName: 'blue', txt: 'синий' },
            { modName: 'beige', txt: 'бежевый' },
            { modName: 'grey', txt: 'серый' },
        ],
        sizes:       [],
        description: [
            { title: 'Детали:', txt: 'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%' },
            { title: 'Как выбрать размер:', txt: 'Написать дяде Рику для уточнения.' },
        ],
    },
];

export { cardsMassive as default };
